### ISSUE TITLE
Beyond regexp selects EVERYTHING :)

### ISSUE THREAD

**Issue by Tvangeste** [xanthics/poe_gen_search_string#2]
Beyond modes (both of them) result in the following regexp to be generated: "cl" (from "close together", I assume).

The problem is that, at least in PoE 3.17.3b, it selects EVERYTHING, all maps, all items, all currencies. It looks like the word "class" is present in every item and "class" regexp matches everything in the stash.

Looks like the regexp for beyond map mode needs to be tweaked, eg: "clo"

Thanks for the great tool, btw!

**Comment by Tvangeste** [comment]
Well, "clo" is not 100% reliable. It also selects my map "Cyclopean Trap" :)

**Comment by xanthics** [comment]
Added `Class` as a bad base name 00c3c8e23979b28fbfaa8fddb8a0cb446a40eda6

I would like to handle all possible map names but still need an authoritative list.
